org: salinsuwu
service: api-alumnos

provider:
  name: aws
  runtime: python3.12
  iam:
    role: arn:aws:iam::164273947020:role/LabRole

functions:
  listar:
    handler: ListarAlumnos.lambda_handler
    events:
      - http:
          path: /alumnos/listar
          method: post
          cors: true
          integration: lambda



